# General
base_url = "https://ced-c.github.io/"
compile_sass = false
minify_html = true
generate_feeds = true
generate_sitemap = true

# Taxonomies
taxonomies = [{ name = "tags", feed = true, paginate_by = 10 }]

# Language
default_language = "fr"

[languages.fr]
build_search_index = true
title = "Mes 2Â¢"
description = "Un blog sans prÃ©tention â€”tapÃ© avec â™¥ sur un clavier"

[markdown]
render_emoji = true
external_links_target_blank = true
smart_punctuation = true

[markdown.highlighting]
# When set to "true", missing highlight languages are treated as errors. Defaults to false but recommended to set to true.
error_on_missing_language = false
light_theme = "github-light"
dark_theme = "github-dark"


[slugify]
paths = "on"
taxonomies = "on"
anchors = "on"

[link_checker]
internal_level = "warn"

# Extra
[extra]
author = "CÃ¦tera"
favicon = "favicon.ico"
list_pages = true
twitter_card = true
enable_search = true

## Navigation
header_nav = [
  { url = "/", name_en = "/home/", name_fr = "ğŸ â€¯accueil" },
  # { url = "/about", name_en = "/about/", name_fr = "/concernant/" },
  # { url = "/journal", name_en = "/journal/", name_fr = "/journal/" },
  { url = "/blog", name_en = "/blog/", name_fr = "ğŸ—’ï¸â€¯blog" },
]
